# https://aka.ms/yaml

trigger:
  branches:
    include:
      - 3.1.2-stable+android

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: android
      image: circleci/android:api-27-ndk
      options: '-u 0'

container: android

steps:
- script: sudo apt-get update && sudo apt-get install scons pkg-config
  displayName: 'Install system deps'

- script: env
  displayName: 'env'

- script: |
    scons platform=android target=release android_arch=armv7
    scons platform=android target=release android_arch=arm64v8
    scons platform=android target=release android_arch=x86
  displayName: 'scons'

- script: |
    cd platform/android/java && ./gradlew build
  displayName: 'build'
