# https://aka.ms/yaml

trigger:
  branches:
    include:
      - 3.1.2-stable+android

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: android
      image: circleci/android:api-27-ndk
      options: '-u 0'

container: android

steps:
- script: |
    sudo apt-get update
    sudo apt-get install scons
  displayName: 'Install scons'

- script: |
    ANDROID_NDK_ROOT=$ANDROID_NDK_HOME scons platform=android target=release android_arch=armv7
    ANDROID_NDK_ROOT=$ANDROID_NDK_HOME scons platform=android target=release android_arch=arm64v8
    ANDROID_NDK_ROOT=$ANDROID_NDK_HOME scons platform=android target=release android_arch=x86
  displayName: 'Run scons'

- script: |
    cd platform/android/java && ANDROID_NDK_ROOT=$ANDROID_NDK_HOME ./gradlew build
    ls -lah bin
  displayName: 'Build'
